### ISSUE TITLE
Doesn't work for dashboards

### ISSUE THREAD

**Issue by hintbw** [kzu/azdo#1]
I find when I try to create a short URL for a dashboard I just end up with the normal URL - (which is a bummer because it has a GUID attached to it). It would be awesome it there was some way to shorten the URL like with the other areas and to add the dashboard name (separated by hyphens) as the end part of the URL

**Comment by kzu** [comment]
Yep, dashboards aren't supported right now. Not sure if you can access a dashboard by name though?

**Comment by kzu** [comment]
Closing for now since the service is (for now?) entirely stateless too: from the original short URL, it constructs the final looong AzDO URL, but there's no storage and/or mapping involved. If AzDO itself doesn't offer a way to access the resource via the information in a shortened URL (i.e. navigate to a dashboard directly from its name, say), then it's much harder to redirect than for other endpoints.

In this particular case, I guess one solution would be to invoke AzDO API (some search endpoint), try to locate the dashboard by name (and/or internal ID if there's a short one we can use), and then return a permanent redirect so we don't consume much resources doing this over and over. But that requires quite a bit more work than the other areas.

So I'll close it for now as there doesn't seem to be a lot of traction for this feature. 

Obviously, a PR would be very much welcomed.

Thanks
