### ISSUE TITLE
Domain (azdo.io) is not reachable anymore

### ISSUE THREAD

**Issue by 24mu13** [kzu/azdo#8]
Sadly there is nothing to add to the subject.

By the way could I ask you if you plan to change to "ado" ? Recently, Microsoft started to use this ambigous acronym in their blog, after years using azdo... 
https://devblogs.microsoft.com/devops/

**Comment by kzu** [comment]
Alive and well: 
![image](https://user-images.githubusercontent.com/169707/236105766-264d91f3-4d23-4b6b-a8e4-d0a8b0be9420.png)

But alas, since there wasn't a SINGLE sponsor to this, I'm archiving the project and letting the domain die. Can't pay a (rather expensive) domain I don't even use anymore (I switched entirely to GH).
